config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resource :session , only: [:new, :create, :destroy]

  get "register" => "users#new", :as => "register"
  get "log_out" => "sessions#destroy", :as => "logout"
  get "log_in" => "sessions#new", :as => "login"
  get "admindashboard" => "admin_dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password


  validates :username, presence: true, uniqueness: true

  validates :email, format:{ with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :fullname, :phonenumber, :password, :password_confirmation, :admin)
    end
end

app/helpers/admin_dashboard_helper.rb
module AdminDashboardHelper
	require 'securerandom'

	def random_avatar_gen
		r = SecureRandom.hex(10)
		image_tag "https://i.pravatar.cc/40?u=#{r}"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def controller_stylesheet_link_tag
		#fail
		stylesheet_link_tag params[:controller], "data-turbo-track": "reload"
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_form.html.erb
<div class="row2">
	
</div>
<div class="row3">
	
</div>

app/views/homes/index.html.erb
<div class="parent">
	<%= render partial: 'banner' %>
	<%= render partial: 'main' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= controller_stylesheet_link_tag %>
<!-- 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_banner.html.erb
<div class="banner">
	<div>
		<div class="logo">
			<%= image_tag 'logo.png' %>
			<div class="textlogo">
				ODIN
			</div>
		</div>
		<div class="footer">
			Photo by Halie West on Unsplashed
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <div class="row1">
    <p>
      <b>This is not a real online service! You know you need something like this in your life you realize your deepest dreams.<br>Sign up <i>now</i> to get started.<br><br><br>You <i>know</i> you want to.</b>
    </p>
  </div>
  <div class="row2">
    <p><b>Let's do this!</b></p>
    <div class="formflex">
      <div>
        <%= form.label :username, "USERNAME", class: "formlabel" %>
        <%= form.text_field :username, autofocus: true, class: "forminput" %>
      </div>

      <div>
        <%= form.label :email, "EMAIL", class: "formlabel" %>
        <%= form.text_field :email, class: "forminput" %>
      </div>

      <div> 
        <%= form.label :fullname, "FULL NAME",class: "formlabel" %>
        <%= form.text_field :fullname, class: "forminput" %>
      </div>

      <div>
        <%= form.label :phonenumber, "PHONE NUMBER",class: "formlabel" %>
        <%= form.number_field :phonenumber, class: "forminput" %>
      </div>

      <div>
        <%= form.label :password, "PASSWORD",class: "formlabel" %>
        <%= form.password_field :password, class: "forminput" %>
      </div>

      <div>
        <%= form.label :password_confirmation, "CONFIRM PASSWORD",class: "formlabel" %>
        <%= form.password_field :password_confirmation, class: "forminput" %>
      </div>
    </div>
  </div>
  <div class="row3">
    <%= form.submit "Register", class: "button_submit" %>
  </div>
  <%= javascript_tag 'passvalidate.js' %>
<% end %>

app/views/users/_main.html.erb
<div class="main">
	<div class="row1">
		<p>
	      <b>This is not a real online service! You know you need something like this in your life you realize your deepest dreams.<br>Sign up <i>now</i> to get started.<br><br><br>You <i>know</i> you want to.</b>
		</p>
	</div>
	<div class="row2 ">
		<%= button_to "Register", register_path, class: "button_register", method: :get %>
		<%= button_to "Login", login_path, class: "button_login",  method: :get%>
	</div>
	<div class="row3">
	  
	 </div>
</div>

app/views/users/_signup.html.erb
<div class="main">
	<div class="row1">
		<p>
	      <b>This is not a real online service! You know you need something like this in your life you realize your deepest dreams.<br>Sign up <i>now</i> to get started.<br><br><br>You <i>know</i> you want to.</b>
		</p>
	</div>
	<div class="row2">
	
	</div>
	<div class="row3">
	  
	 </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Fullname:</strong>
    <%= user.fullname %>
  </p>

  <p>
    <strong>Phonenumber:</strong>
    <%= user.phonenumber %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="parent">
  <%= render partial: 'banner' %>
  <%= render partial: 'main' %>
</div>
<!-- <p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>
 -->

app/views/users/new.html.erb
<div class="parent">
  <%= render partial: 'banner' %>
  <%= render 'form', user: @user %>
</div>
<!-- <h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div> -->

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>